---
http_interactions:
- request:
    method: post
    uri: https://sandbox.extra.com.br/api/v1/product
    body:
      encoding: UTF-8
      string: "{\"id\":\"extra-ruby-2\",\"name\":\"Extra Ruby\",\"sku\":[{\"id\":\"extra-ruby-2\",\"name\":\"Extra
        Ruby\",\"ean\":[\"invalid\"],\"weight\":1,\"stockQuantity\":3,\"enable\":true,\"price\":{\"sellPrice\":10,\"listPrice\":10}}],\"manufacturer\":{\"name\":\"Digital
        Pages\",\"model\":\"extra-ruby\",\"warrantyTime\":1},\"deliveryType\":\"SHIPMENT\",\"nbm\":{\"number\":\"49019900\",\"origin\":\"1\"}}"
    headers:
      Accept:
      - "*/*; q=0.5, application/xml"
      Accept-Encoding:
      - gzip, deflate
      Content-Type:
      - application/json
      Nova-Auth-Token:
      - WOzY6C8kEFGM
      Nova-App-Token:
      - OmehvO0ZHM2s
      Content-Length:
      - '337'
      User-Agent:
      - Ruby
  response:
    status:
      code: 404
      message: Not Found
    headers:
      Date:
      - Wed, 14 May 2014 15:24:19 GMT
      Server:
      - Apache
      Content-Length:
      - '66'
      X-Powered-By:
      - Servlet/2.5 JSP/2.1
      Content-Type:
      - binary/octet-stream; charset=utf-8
    body:
      encoding: UTF-8
      string: 'Cannot find a route for this request: sandbox.extra.com.br product'
    http_version: 
  recorded_at: Wed, 14 May 2014 15:24:19 GMT
recorded_with: VCR 2.8.0
